spark.master                                        spark://spark-master:7077
spark.sql.session.timeZone                          UTC
spark.sql.streaming.checkpointLocation              /tmp/spark-checkpoints
spark.sql.adaptive.enabled                          true
spark.sql.adaptive.coalescePartitions.enabled       true
spark.serializer                                    org.apache.spark.serializer.KryoSerializer
