apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: trading
      defaultBucket: market_data
      tlsSkipVerify: true
    secureJsonData:
      token: trading-token-123
    isDefault: true
    editable: true
